import React, { useEffect } from 'react';
import { ScrollText, CheckCircle2, AlertCircle, FileText, Briefcase, Scale, Globe, Video } from 'lucide-react';
import { motion } from 'framer-motion';

const rules = [
  {
    icon: <Briefcase className="w-6 h-6 text-[rgb(var(--accent))]" />,
    title: "Use of Platform",
    content: "Interview AI provides tools for interview preparation. You agree to use these tools solely for personal, non-commercial educational purposes. You may not reverse-engineer, scrape, or systematically extract data from our platform."
  },
  {
    icon: <CheckCircle2 className="w-6 h-6 text-[rgb(var(--accent))]" />,
    title: "User Accounts",
    content: "You are responsible for maintaining the confidentiality of your account credentials. You agree to notify us immediately of any unauthorized use of your account. We reserve the right to suspend or terminate accounts that violate our terms."
  },
  {
    icon: <FileText className="w-6 h-6 text-[rgb(var(--accent))]" />,
    title: "Content Generation",
    content: "Our AI generates interview questions and feedback. While we strive for accuracy, AI-generated content is provided 'as is' without warranties. You should not rely solely on AI feedback for critical career decisions."
  },
  {
    icon: <Scale className="w-6 h-6 text-[rgb(var(--accent))]" />,
    title: "Intellectual Property",
    content: "All platform design, code, algorithms, and original content are owned by Interview AI. User-uploaded resumes and answers remain your intellectual property, but you grant us a license to process them for the purpose of providing the service."
  },
  {
    icon: <Globe className="w-6 h-6 text-[rgb(var(--accent))]" />,
    title: "Content Sources & Accuracy",
    content: "Content displayed on the Interview AI platform is either generated by Artificial Intelligence or curated from public internet resources. We do not guarantee the absolute accuracy, completeness, or reliability of any information provided."
  },
  {
    icon: <Video className="w-6 h-6 text-[rgb(var(--accent))]" />,
    title: "Third-Party Resources & Educational Use",
    content: "Notes, resources, and embedded media (such as YouTube videos) are provided strictly for educational purposes. We are not sponsored by, endorsed by, or affiliated with the original content creators or channels. All third-party copyrights belong to their respective owners."
  }
];

const TermsAndConditions = () => {
  useEffect(() => {
    window.scrollTo(0, 0);
  }, []);

  return (
    <div className="min-h-screen bg-[rgb(var(--bg-body))] text-[rgb(var(--text-primary))] py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center justify-center p-3 bg-[rgb(var(--accent))]/10 rounded-full mb-4">
            <ScrollText className="w-8 h-8 text-[rgb(var(--accent))]" />
          </div>
          <h1 className="text-3xl sm:text-5xl font-bold mb-4 tracking-tight">Terms and Conditions</h1>
          <p className="text-[rgb(var(--text-muted))] text-lg">
            Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
          </p>
        </motion.div>

        <div className="bg-[rgb(var(--bg-card))] border border-[rgb(var(--border))] rounded-2xl shadow-sm p-6 sm:p-10 space-y-10">
          
          <motion.section 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.2 }}
            className="prose prose-invert max-w-none text-[rgb(var(--text-secondary))]"
          >
            <p className="text-lg leading-relaxed bg-[rgb(var(--accent))]/5 p-4 rounded-lg border-l-4 border-[rgb(var(--accent))]">
              Please read these terms and conditions carefully before using our service. By accessing or using the Interview AI platform, you agree to be bound by these Terms and accept all legal consequences. If you do not agree to these terms and conditions, in whole or in part, please do not use the service.
            </p>
          </motion.section>

          <div className="space-y-6">
            {rules.map((rule, index) => (
              <motion.div 
                key={index}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 * index + 0.3 }}
                className="flex flex-col sm:flex-row gap-4 p-6 bg-[rgb(var(--bg-body-alt))] rounded-xl border border-[rgb(var(--border))]/50"
              >
                <div className="flex-shrink-0">
                  <div className="p-3 bg-[rgb(var(--bg-card))] rounded-full shadow-sm">
                    {rule.icon}
                  </div>
                </div>
                <div>
                  <h3 className="text-xl font-semibold text-[rgb(var(--text-primary))] mb-2">{rule.title}</h3>
                  <p className="text-[rgb(var(--text-secondary))] leading-relaxed">
                    {rule.content}
                  </p>
                </div>
              </motion.div>
            ))}
          </div>

          <motion.div 
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.7 }}
            className="mt-8 p-6 border border-[rgb(var(--border))] rounded-xl bg-red-500/5"
          >
            <div className="flex items-start gap-3">
              <AlertCircle className="w-6 h-6 text-red-500 flex-shrink-0 mt-1" />
              <div>
                <h3 className="text-lg font-semibold text-red-500 mb-2">Limitation of Liability</h3>
                <p className="text-[rgb(var(--text-secondary))] text-sm leading-relaxed">
                  In no event shall Interview AI, nor its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential or punitive damages, including without limitation, loss of profits, data, use, goodwill, or other intangible losses, resulting from your access to or use of or inability to access or use the Service.
                </p>
              </div>
            </div>
          </motion.div>

        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
